name: CI

# Triggers the workflow on push or pull request events
on:
  push:
    branches: ['*']

  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches: ['*']

jobs:
  build:

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: true
      max-parallel: 1024
      matrix:
        os: [ubuntu-20.04]
        node-version: [v14.15.1]
        experimental: [false]
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/checkout@v2.3.4

    - run: npm ci
    - run: npm test
